### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException at com.jcraft.jsch.Buffer.putByte(Buffer.java:56)

### ISSUE THREAD

**Issue by OLeh125** [quarkiverse/quarkus-jsch#115]
Hi, I use 
![image](https://github.com/quarkiverse/quarkus-jsch/assets/55195530/b4fd17ac-59d1-4ef2-9a19-295648bd01f5)
and periodically face with java.lang.ArrayIndexOutOfBoundsException when connect to jsch session 
![image](https://github.com/quarkiverse/quarkus-jsch/assets/55195530/7a1db2bb-eb12-4c0e-a004-4ee3e55bd957)
What could be the root cause? And is this fixed in latest versions?

**Comment by gastaldi** [comment]
Can you reproduce that in a test case?

**Comment by gastaldi** [comment]
Looks like it's the same reported in https://github.com/mwiede/jsch/issues/237?

**Comment by OLeh125** [comment]
Ok, thanks
