### ISSUE TITLE
com.jcraft.jsch.jzlib.Compression not included in native compilation

### ISSUE THREAD

**Issue by gnieser** [quarkiverse/quarkus-jsch#118]
Hello,

The class com.jcraft.jsch.jzlib.Compression is missing from the Quarkus JSch when compiling to native.

I'm using a Quarkus Camel route with SFTP component and compression level at 9.
```
Caused by: java.lang.ClassNotFoundException: com.jcraft.jsch.jzlib.Compression
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:123)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:87)
	at java.base@17.0.9/java.lang.Class.forName(DynamicHub.java:1322)
	at java.base@17.0.9/java.lang.Class.forName(DynamicHub.java:1285)
	at java.base@17.0.9/java.lang.Class.forName(DynamicHub.java:1278)
	at com.jcraft.jsch.Session.initDeflater(Session.java:2493)
	... 21 more
```

It is used by reflection in JSch session when initializing an [inflater](https://github.com/mwiede/jsch/blob/2dd6dc2628370c21dd34349eacb5be64d7bd949b/src/main/java/com/jcraft/jsch/Session.java#L2526) or a [deflater](https://github.com/mwiede/jsch/blob/2dd6dc2628370c21dd34349eacb5be64d7bd949b/src/main/java/com/jcraft/jsch/Session.java#L2493C52).
The class corresponds to the use of zlib compression as defined in the [JSch config map](https://github.com/mwiede/jsch/blob/2dd6dc2628370c21dd34349eacb5be64d7bd949b/src/main/java/com/jcraft/jsch/JSch.java#L189-L190)

I think it should be added to the [JSchProcessor](https://github.com/quarkiverse/quarkus-jsch/blob/229dbf8074d351eeb0d4eac2ee89cb17aaebc7ee/deployment/src/main/java/io/quarkus/jsch/deployment/JSchProcessor.java#L30) of quarkus-jsch extension.

So far I'm using as a workaround an explicit registration for reflection.
```java
@RegisterForReflection(targets = {com.jcraft.jsch.jzlib.Compression.class})
public class JSchCompressionReflectionConfiguration {
}
```

Thanks

**Comment by gastaldi** [comment]
Thanks for the issue, want to submit a PR with the fix?

**Comment by gnieser** [comment]
I would love to. But would only be able to if my windows workstation let me run the native integration tests, which currently my setup fails to do (complaining about a cl.exe missing...)

**Comment by gastaldi** [comment]
@gnieser you can rely on our CI to do that: start by creating the test that reproduces your problem and see if CI breaks in a PR, then introduce the fix in a second commit

**Comment by gnieser** [comment]
I've been using WSL2 with Ubuntu distro along with sdkman for a quick setup of mandrel and maven.

**Comment by gastaldi** [comment]
Fixed in https://github.com/quarkiverse/quarkus-jsch/pull/120
