### ISSUE TITLE
Is there documentation and demo for this extension?

### ISSUE THREAD

**Issue by janyyy** [quarkiverse/quarkus-jsch#20]
Is there documentation and demo for this extension? Are you considering using a connection pool to manage connections?

**Comment by gastaldi** [comment]
@janyyy this extension only enables JSch to be compiled to native. You can look at the integration tests if you're looking for an example on how to use JSch, but I think you'll find more examples in http://www.jcraft.com/jsch/

**Comment by gastaldi** [comment]
The current extension documentation lies in https://quarkiverse.github.io/quarkiverse-docs/quarkus-jsch/dev/index.html
