### ISSUE TITLE
Switch to com.github.mwiede:jsch 

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-jsch#23]
... for reasons named in https://www.matez.de/index.php/2020/06/22/the-future-of-jsch-without-ssh-rsa/

**Comment by gsmet** [comment]
Do we need to do it now?

I’m always a bit nervous when switching some security component to a new artifact coming out of the blue. 
That’s how good supply chain attacks usually start. 

If it’s not pressing, I would wait for a bit.

**Comment by ppalaga** [comment]
We (Camel Quarkus) would prefer getting this not earlier than Quarkus 2.9. 
A similar migration is in progress in Camel by @ggrzybek in https://github.com/apache/camel/pull/7241 . That one is scheduled for Camel 3.17 that still does not have an ETA.

**Comment by jamesnetherton** [comment]
Are we likely to get this done any time soon? While there's some divergence between this extension and Camel, we have to maintain some workarounds in Camel Quarkus. Which I'd like to avoid doing across multiple releases if possible.

**Comment by gsmet** [comment]
If you're confident this is a safe move then I suppose we should do it, provided @gastaldi agrees.

**Comment by gastaldi** [comment]
+1, that makes sense. 

Have anyone tried simply replacing it to verify if any tests fail?

**Comment by jamesnetherton** [comment]
> Have anyone tried simply replacing it to verify if any tests fail?

Seems there are some extra classes that need to be registered for reflection as the native itests fail. I could try to take a look into it next week and create a PR after I'm done with the CQ 2.9.0 release.
