### ISSUE TITLE
Upgrade to Quarkus 3

### ISSUE THREAD

**Issue by ppalaga** [quarkiverse/quarkus-jsch#77]
It should not be so hard. From what I see ony the JAX-RS enspoint in the test module needs to be changed from `import javax.` to `import jakarta.`.

Quarkus migration tips: https://github.com/quarkiverse/quarkiverse/wiki/Migrating-to-Quarkus-3.x

**Comment by gastaldi** [comment]
So 2.0.4 can be used in Quarkus 3 without any code changes, since the integration tests are not part of the extension

**Comment by ppalaga** [comment]
The fix is underway.
